backend:
  name: git-gateway
  repo: h1kupz/fvm-sosmed
  branch: main

site_url: https://fvm-sosmed.netlify.app
display_url: https://fvm-sosmed.netlify.app
logo_url: https://fvm-sosmed.netlify.app/assets/fvm.png

media_folder: public/images
public_folder: /images

collections:
  - name: partnerships
    label: Partnerships
    folder: /src/content/partnerships
    format: frontmatter
    create: true
    fields:
      - name: chain
        label: Chain
        widget: select
        options: ["bvm", "cvm", "fvm", "mvm"]
      - { name: title, label: Title/Filename (Please add chain to front of title - ie. fvm/cvm/...), widget: string }
      - {
          name: bgImage,
          label: Background Image,
          widget: image,
          choose_url: true,
          required: true,
        }
      - { name: tLogo, label: Top Partner Logo, widget: image }
      - { name: logo, label: Main Partner Logo, widget: image }

  - name: aprs
    label: APRs
    folder: /src/content/aprs
    format: frontmatter
    create: true
    fields:
      - name: chain
        label: Chain
        widget: select
        options: ["bvm", "cvm", "fvm", "mvm"]
      - { name: title, label: Title/Filename (Please add chain to front of title - ie. fvm/cvm/...), widget: string }
      - { name: header1, label: Header 1, widget: string }
      - { name: header2, label: Header 2, widget: string }
      - { name: header3, label: Header 3, widget: string }
      - {
          name: bgImage,
          label: Background Image,
          widget: image,
          choose_url: true,
          required: true,
        }
      - name: items
        label: Number of Cards
        widget: select
        options: ["oneCard", "twoCard", "threeCard"]
      - {
          name: item1,
          label: Card 1,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
              { name: apr, label: APR, widget: string },
              { name: tvl, label: TVL, widget: string },
            ],
        }
      - {
          name: item2,
          label: Card 2,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
              { name: apr, label: APR, widget: string },
              { name: tvl, label: TVL, widget: string },
            ],
        }
      - {
          name: item3,
          label: Card 3,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
              { name: apr, label: APR, widget: string },
              { name: tvl, label: TVL, widget: string },
            ],
        }

  - name: partnerbribes
    label: Partner Bribes
    folder: /src/content/partnerbribes
    format: frontmatter
    create: true
    fields:
      - name: chain
        label: Chain
        widget: select
        options: ["bvm", "cvm", "fvm", "mvm"]
      - { name: title, label: Title/Filename (Please add chain to front of title - ie. fvm/cvm/...), widget: string }
      - { name: header, label: Header, widget: string }
      - {
          name: bgImage,
          label: Background Image,
          widget: image,
          choose_url: true,
          required: true,
        }
      - { name: logo, label: Partner Logo, widget: image }
      - { name: total, label: Bribe Total, widget: string }
      - name: items
        label: Number Pairs Bribed
        widget: select
        options: ["oneBribe", "twoBribe", "threeBribe"]
      - {
          name: item1,
          label: Bribe Pair 1,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
            ],
        }
      - {
          name: item2,
          label: Bribe Pair 2,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
            ],
        }
      - {
          name: item3,
          label: Bribe Pair 3,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
            ],
        }

  - name: matchedbribes
    label: Matched Bribes
    folder: /src/content/matchedbribes
    format: frontmatter
    create: true
    fields:
      - name: chain
        label: Chain
        widget: select
        options: ["bvm", "cvm", "fvm", "mvm"]
      - { name: title, label: Title/Filename (Please add chain to front of title - ie. fvm/cvm/...), widget: string }
      - {
          name: bgImage,
          label: Background Image,
          widget: image,
          choose_url: true,
          required: true,
        }
      - { name: briber, label: Briber, widget: string }
      - { name: logo, label: Logo, widget: image }
      - { name: total, label: Total, widget: string }
      - {
          name: item1,
          label: Bribes,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: ttl1, label: Total 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
              { name: ttl2, label: Total 2, widget: string },
            ],
        }
      - {
          name: item2,
          label: Pair,
          widget: object,
          fields:
            [
              { name: tkn1, label: Token 1, widget: image },
              { name: tkr1, label: Ticker 1, widget: string },
              { name: tkn2, label: Token 2, widget: image },
              { name: tkr2, label: Ticker 2, widget: string },
              { name: apr, label: Projected APR, widget: string },
            ],
        }

  - name: totalbribes
    label: Total Bribes
    folder: /src/content/totalbribes
    format: frontmatter
    create: true
    fields:
      - name: chain
        label: Chain
        widget: select
        options: ["bvm", "cvm", "fvm", "mvm"]
      - { name: title, label: Title/Filename (Please add chain to front of title - ie. fvm/cvm/...), widget: string }
      - {
          name: bgImage,
          label: Background Image,
          widget: image,
          choose_url: true,
          required: true,
        }
      - { name: epoch, label: Epoch, widget: string }
      - { name: total, label: Total Bribes, widget: string }
