backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "aprs"
    label: "APRs"
    folder: "src/content/aprs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
