backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - label: "APRs"
    name: "aprs"
    folder: "src/content/aprs"
    format: "frontmatter"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Header, name: header, widget: string }
      - {
          label: "Background Image",
          name: "bgImage",
          widget: "image",
          choose_url: true,
          required: true,
        }
